# Generated by Django 3.0.2 on 2020-02-14 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desktop',
            name='status',
            field=models.CharField(choices=[('Available', 'Item ready to be purchased'), ('Sold', 'Item Sold'), ('Restock', 'Item restock in few Days')], default='SOLD', max_length=10),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='status',
            field=models.CharField(choices=[('Available', 'Item ready to be purchased'), ('Sold', 'Item Sold'), ('Restock', 'Item restock in few Days')], default='SOLD', max_length=10),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='status',
            field=models.CharField(choices=[('Available', 'Item ready to be purchased'), ('Sold', 'Item Sold'), ('Restock', 'Item restock in few Days')], default='SOLD', max_length=10),
        ),
    ]
